services:
  - type: web
    name: green-david-app
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.6
      - key: FLASK_ENV
        value: production
    disk:
      name: green-david-data
      mountPath: /opt/render/project/src
      sizeGB: 1
